{% set name = "collections-extended" %}
{% set version = "2.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/collections-extended-{{ version }}.tar.gz
  sha256: d68ebd1e2208444e392aa0016e5c085bd897f89296f5c1860787de5935994114

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python {{ python_min }}
  run:
    - python >={{ python_min }}

test:
  imports:
    - collections_extended
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/mlenzen/collections-extended
  doc_url: https://collections-extended.lenzm.net/
  summary: Extra Python Collections - bags (multisets) and setlists (ordered sets)
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
